[package]
name = "vergen-cl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
vergen-pretty = { version = "0.3.3", features = ["color"] }

[build-dependencies]
anyhow = "1.0.79"
vergen-gix = { version = "1.0.0-beta.2", default-features = false, features = [
    "build",
    "cargo",
    "rustc",
    "si"
] }
