[package]
name = "vergen-cl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
anyhow = "1.0.75"
vergen = { version = "8.2.5", default-features = false, features = [
    "build",
    "cargo",
    "git",
    "gitcl",
] }
