[package]
name = "vergen-cl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
unstable = []

[dependencies]
anyhow = "1.0.86"
vergen-pretty = { version = "0.3.4", features = ["color"] }

[build-dependencies]
anyhow = "1.0.86"
rustversion = "1.0.17"
vergen-gix = { version = "1.0.0", default-features = false, features = [
    "build",
    "cargo",
    "rustc",
    "si"
] }
