[package]
name = "vergen-cl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
vergen-pretty = "0.3.0"

[build-dependencies]
anyhow = "1.0.79"
vergen = { version = "8.2.9", default-features = false, features = [
    "build",
    "cargo",
    "git",
    "gitoxide",
    "rustc",
    "si"
] }
